export const PATCH_TASKS = "PATCH_TASKS";
export const SET_CURRENT_TASK = "SET_CURRENT_TASK";
export const START_TIMER = "START_TIMER";
export const UPDATE_TIMER = "UPDATE_TIMER";
export const PAUSE_TIMER = "PAUSE_TIMER";

export const REFRESH_REQUEST = "REFRESH_REQUEST";
export const PATCH_TASKS_REQUEST = "PATCH_TASKS_REQUEST";
export const SET_CURRENT_TASK_REQUEST = "SET_CURRENT_TASK_REQUEST";
export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const START_TIMER_REQUEST = "START_TIMER_REQUEST";
export const UPDATE_TIMER_REQUEST = "UPDATE_TIMER_REQUEST";
export const PAUSE_TIMER_REQUEST = "PAUSE_TIMER_REQUEST";
export const SAVE_REQUEST = "SAVE_REQUEST";
